
-- WHY AN ARBITER'S REASONING NEEDS A HOME.
--
-- When a human settles a dispute they write why. That sentence was being saved
-- to localStorage in the browser of whoever resolved it, and the contract's
-- DisputeResolved event carries the amounts but not the reason — so it existed
-- in exactly one place, on one machine, belonging to one party.
--
-- The client could read it. The freelancer, whose payment it had just decided,
-- could not, from any device, ever. A decision one side can read and the other
-- cannot is not arbitration.
--
-- One row per milestone, because a milestone is resolved once. The amounts stay
-- on-chain where they belong; this is only the explanation beside them.

create table if not exists public.dispute_resolutions (
  id                bigint generated by default as identity primary key,
  escrow_id         bigint      not null,
  milestone_index   integer     not null,
  arbiter_address   text        not null,
  reason            text        not null,
  resolved_at       timestamptz not null default now(),
  unique (escrow_id, milestone_index)
);

create index if not exists dispute_resolutions_escrow
  on public.dispute_resolutions (escrow_id);

alter table public.dispute_resolutions enable row level security;

-- Readable by anyone: it explains a payment between two named parties, settled
-- on a public chain where the amounts are already visible. Keeping the reason
-- behind a login while the money is open protects nobody.
create policy "public read dispute resolutions"
  on public.dispute_resolutions for select using (true);

-- Written only through the API, which verifies twice over that the writer is
-- the arbiter named in the on-chain DisputeResolved event for that exact
-- milestone. No anon insert: without that check, the reasoning behind somebody
-- else's payment would be a thing strangers could author.
create policy "service role writes dispute resolutions"
  on public.dispute_resolutions for all
  to service_role using (true) with check (true);
